### ISSUE TITLE
scala 2.12.*?

### ISSUE THREAD

**Issue by unthingable** [codacy/bitbucket-scala-client#21]
`crossScalaVersions := Seq("2.10.5", "2.11.7")`

**Comment by mrfyda** [comment]
I think we'll have to wait for a Play 2.12 compatible release, since we depend on play-ws:
`"com.typesafe.play" %% "play-ws" % "2.4.3"`

**Comment by unthingable** [comment]
Fair enough!

**Comment by mucahitkantepe** [comment]
Play 2.6 supports 2.12, I think this is the right time.

**Comment by rtfpessoa** [comment]
@mucahitkantepe I am re-opening this, but at the moment we do not have time to change this. PRs are welcome.
