### ISSUE TITLE
'!' in the API url

### ISSUE THREAD

**Issue by zamblauskas** [codacy/bitbucket-scala-client#28]
Hey guys,
I've used your client for a batch webhook update on all of our BitBucket repos.  
I refactored authentication to also support AppPassword method, but had to remove all the  '!' from the urls, otherwise was getting `401 unauthorized` from BitBucket.

Why was the '!' needed in the first place, cannot find anything on BitBucket docs ?

Related commits:
https://github.com/zamblauskas/bitbucket-scala-client/commit/43f9fd54e073005d0009b0e55fcbc845bf4069b9
https://github.com/zamblauskas/bitbucket-scala-client/commit/2ed4d572c0d641edfd82f44cac5c1b5f685cedf9

If you would confirm that '!' is not needed, I'd be glad to create a PR for the AppPassword authentication method.

**Comment by mrfyda** [comment]
Nice catch. 👍 

> !api is only meant to be used by the bitbucket UI itself. It only works with a restricted set of authentication types

According to this PR: https://bitbucket.org/atlassian/atlassian-connect-express/pull-requests/109/use-apibitbucketorg-instead-of-api/diff

Feel free to create a pull request with your changes!

**Comment by zamblauskas** [comment]
Thanks for the response.
